import avater10 from '../../../assets/avaters/avatar_10.jpg';
import avater12 from '../../../assets/avaters/avatar_12.jpg';
import avater14 from '../../../assets/avaters/avatar_14.jpg';
import avater17 from '../../../assets/avaters/avatar_17.jpg';
import avater25 from '../../../assets/avaters/avatar_25.jpg';

export const studentData = [
  {
    id: 1,
    name: 'John Doe',
    class: 'Class 1',
    section: 'Section A',
    branch: 'Addis Ababa Aware Branch',
    avatar: avater10,
    age: 16,
    gender: 'Male',
    address: '123 Main Street',
    email: 'john.doe@example.com',
    phone: '+1 555-123-4567',
    FatherName: 'Abele Jane ',
    FatherPhone:'9554664667',
    FatherEmail: 'jane.doe@example.com',
    FatherOccupation: 'BUSINESS',
    MotherName: 'S K CHOUHAN',
    MotherPhone: '+1 555-987-6543',
    motherOccupation: 'BUSINESS',
    GuardianName:'B K CHOUHAN',
    GuardianEmail:'tbk15@gmail.com',
    GuardianPhone:'9554664667',
    FatherAvatar:avater14,
    MotherAvatar:avater25,
    GuardianAvatar:avater17,
    status: 'Banned',
    admissionNo:'125452',
    rollNumber:'23658542',
    MultiClass:'true',
    category:'General',
    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 10 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
    ],
  },
  {
    id: 2,
    name: 'Jane Smith',
    class: 'Class 2',
    section: 'Section B',
    branch: 'Addis Ababa Aware Branch',
    avatar: avater14,
    age: 15,
    gender: 'Female',
    address: '456 Elm Street',
    email: 'jane.smith@example.com',
    phone: '+1 555-234-5678',
    parentName: 'John Smith',
    parentEmail: 'john.smith@example.com',
    parentPhone: '+1 555-876-5432',
    parentAvatar:avater14,
    status: 'Banned',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'General',

    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 30 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      { courseId: 4, courseName: 'chemistry', progress: 70 },
      { courseId: 5, courseName: 'Biology', progress: 15 },
      // Add more courses as needed
    ],
  },
  {
    id: 3,
    name: 'Alice Johnson',
    class: 'Class 1',
    section: 'Section A',
    branch: 'Addis Ababa Aware Branch',
    avatar: avater25,
    age: 17,
    gender: 'Female',
    address: '789 Oak Avenue',
    email: 'alice.johnson@example.com',
    phone: '+1 555-345-6789',
    parentName: 'David Johnson',
    parentEmail: 'david.johnson@example.com',
    parentPhone: '+1 555-765-4321',
    parentAvatar:avater14,
    status: 'Banned',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'General',
    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],

  },
  {
    id: 4,
    name: 'Bob Brown',
    class: 'Class 3',
    section: 'Section C',
    branch: 'Branch 3',
    avatar: avater12,
    age: 14,
    gender: 'Male',
    address: '321 Pine Lane',
    email: 'bob.brown@example.com',
    phone: '+1 555-876-5432',
    parentName: 'Emily Brown',
    parentEmail: 'emily.brown@example.com',
    parentPhone: '+1 555-234-5678',
    parentAvatar:avater14,
    status: 'Active',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'General',

    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 5,
    name: 'Abebe Zenash Wilson',
    class: 'Class 2',
    section: 'Section B',
    branch: 'Diredewa Branch',
    avatar: avater17,
    age: 16,
    gender: 'Male',
    address: '987 Cedar Street',
    email: 'abebe.wilson@example.com',
    phone: '+1 555-567-8901',
    parentName: 'Zenebe Wilson',
    parentEmail: 'zenebe.wilson@example.com',
    parentPhone: '+1 555-901-2345',
    parentAvatar:avater14,
    status: 'Active',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'General',

    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 6,
    name: 'Emma Davis',
    class: 'Class 3',
    section: 'Section C',
    branch: 'Addis Ababa Weyra Branch',
    avatar: avater10,
    age: 15,
    gender: 'Female',
    address: '654 Maple Drive',
    email: 'emma.davis@example.com',
    phone: '+1 555-678-9012',
    parentName: 'Michael Davis',
    parentEmail: 'michael.davis@example.com',
    parentPhone: '+1 555-345-6789',
    parentAvatar:avater14,
    status: 'Active',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'General',

    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 7,
    name: 'James Johnson',
    class: 'Class 1',
    section: 'Section A',
    branch: 'Addis Ababa Aware Branch',
    avatar: avater17,
    age: 16,
    gender: 'Male',
    address: '789 Oak Avenue',
    email: 'james.johnson@example.com',
    phone: '+1 555-789-0123',
    parentName: 'David Johnson',
    parentEmail: 'david.johnson@example.com',
    parentPhone: '+1 555-901-2345',
    parentAvatar:avater14,
    status: 'Banned',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'General',

    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 8,
    name: 'Sophia Martinez',
    class: 'Class 2',
    section: 'Section B',
    branch: 'Addis Ababa Lebu Branch',
    avatar: avater17,
    age: 15,
    gender: 'Female',
    address: '987 Cedar Street',
    email: 'sophia.martinez@example.com',
    phone: '+1 555-901-2345',
    parentName: 'Carlos Martinez',
    parentEmail: 'carlos.martinez@example.com',
    parentPhone: '+1 555-678-9012',
    parentAvatar:avater14,
    status: 'Active',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'General',

    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 9,
    name: 'Oliver Wilson',
    class: 'Class 3',
    section: 'Section C',
    branch: 'Addis Ababa Aware Branch',
    avatar: avater25,
    age: 17,
    gender: 'Male',
    address: '654 Maple Drive',
    email: 'oliver.wilson@example.com',
    phone: '+1 555-234-5678',
    parentName: 'Zenebe Wilson',
    parentEmail: 'zenebe.wilson@example.com',
    parentPhone: '+1 555-567-8901',
    parentAvatar:avater14,
    status: 'Active',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'General',
    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 10,
    name: 'Emily Anderson',
    class: 'Class 1',
    section: 'Section A',
    branch: 'Addis Ababa Aware Branch',
    avatar: avater14,
    age: 16,
    gender: 'Female',
    address: '123 Main Street',
    email: 'emily.anderson@example.com',
    phone: '+1 555-567-8901',
    parentName: 'Daniel Anderson',
    parentEmail: 'daniel.anderson@example.com',
    parentPhone: '+1 555-901-2345',
    parentAvatar:avater14,
    status: 'Active',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'OBC',
    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 11,
    name: 'William Thompson',
    class: 'Class 2',
    section: 'Section B',
    branch: 'Addis Ababa Aware Branch',
    avatar: avater10,
    age: 15,
    gender: 'Male',
    address: '456 Elm Street',
    email: 'william.thompson@example.com',
    phone: '+1 555-789-0123',
    parentName: 'Sarah Thompson',
    parentEmail: 'sarah.thompson@example.com',
    parentPhone: '+1 555-234-5678',
    parentAvatar:avater14,
    status: 'Active',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'General',
    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 12,
    name: 'Mia Davis',
    class: 'Class 3',
    section: 'Section C',
    branch: 'Branch 3',
    avatar: avater12,
    age: 14,
    gender: 'Female',
    address: '789 Oak Avenue',
    email: 'mia.davis@example.com',
    phone: '+1 555-901-2345',
    parentName: 'Michael Davis',
    parentEmail: 'michael.davis@example.com',
    parentPhone: '+1 555-567-8901',
    parentAvatar:avater14,
    status: 'Active',
    admissionNo:'125452',
    rollNumber:'23658542',
    category: 'Spacial',
    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 13,
    name: 'Jacob Wilson',
    class: 'Class 1',
    section: 'Section A',
    branch: 'Addis Ababa Aware Branch',
    avatar: avater10,
    age: 16,
    gender: 'Male',
    address: '987 Cedar Street',
    email: 'jacob.wilson@example.com',
    phone: '+1 555-234-5678',
    parentName: 'Zenebe Wilson',
    parentEmail: 'zenebe.wilson@example.com',
    parentPhone: '+1 555-789-0123',
    parentAvatar:avater17,
    status: 'Banned',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'Physical Damaged',
    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  },
  {
    id: 14,
    name: 'Lily Rodriguez',
    class: 'Class 2',
    section: 'Section B',
    branch: 'Addis Ababa Lebu Branch',
    avatar: avater17,
    age: 15,
    gender: 'Female',
    address: '654 Maple Drive',
    email: 'lily.rodriguez@example.com',
    phone: '+1 555-901-2345',
    parentName: 'Carlos Rodriguez',
    parentEmail: 'carlos.rodriguez@example.com',
    parentPhone: '+1 555-234-5678',
    parentAvatar:avater12,
    status: 'Active',
    admissionNo:'125452',
    rollNumber:'23658542',
    category:'Physical Damaged',
    courses: [
      { courseId: 1, courseName: 'Mathematics', progress: 70 },
      { courseId: 2, courseName: 'Science', progress: 85 },
      { courseId: 3, courseName: 'History', progress: 50 },
      // Add more courses as needed
    ],
  }]

// JSON array containing tab labels
export const tabLabels = [
  { label: 'Profile' },
  { label: 'Exam' },
  { label: 'Attendance' },
  { label: 'Document' },
  { label: 'Student Behaviour' },
  { label: 'Time Line' },
];

export const Branch=[
  "Awara Branch",
  "Lebu Branch",
  "Wera Branch",
  "C.M.C Branch",
  "Kality Branch",
  "Diredewa Branch",
  "Bahrdar Branch",
];
export let StudentCategoryList=[
  {id:1,name: 'General' },
  {id:2,name: 'OBC' },
  {id:3,name: 'Physical Damaged' },
  { id:4,name:'spacial' }
];
export const BloodGroup = [
  { id: 1, value: 'O+' },
  { id: 2, value: 'A+' },
  { id: 3, value: 'B+' },
  { id: 4, value: 'AB+' },
  { id: 5, value: 'O-' },
  { id: 6, value: 'A-' },
  { id: 7, value: 'B-' },
  { id: 8, value: 'AB-' }
];

export const Report=[
  {id:1,type:'StudentInformation',children:[
      {id:1,name:'Student Report'},
      {id:2,name:'Guardian Report'},
      {id:3,name:'Student Login Credential'},
      {id:4,name:'Class Subject Report'},
      {id:5,name:'Student Gender Ratio Report'},
      {id:6,name:'Class And Section Report'},
      {id:7,name:'Student History Report'},
      {id:8,name:'Parent Login Credential'},
      {id:9,name:'Admission  Report'},
      {id:10,name:'Student Profile'},
    ]}
]
